spring:
  #heroku datasource
  datasource:
    url: jdbc:postgresql://ec2-54-83-50-145.compute-1.amazonaws.com:5432/dkmmf1cu3r9hn?useSSL=false
    username: nfmulsmwahrjqi
    password: c0f675496823c1bac63ff059192cfba00acb2fae6bc4a4a31933443616e143e3
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false

omdbapi:
  apikey: b1e85577
  url: http://www.omdbapi.com/

telegram:
  bot: movie_notify_bot

logging:
  level:
    com:
      ness: info

server:
  port: 8080