spring:
  #heroku datasource
  datasource:
    url: jdbc:postgresql://ec2-54-83-50-145.compute-1.amazonaws.com:5432/dkmmf1cu3r9hn?useSSL=false
    username: nfmulsmwahrjqi
    password: c0f675496823c1bac63ff059192cfba00acb2fae6bc4a4a31933443616e143e3
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false

tmdbapi:
  url: http://api.themoviedb.org/3/
  apikey: d6d669ef1d4e1efa83890eef2dda482f

telegram:
  bot: movie_notify_bot

logging:
  level:
    com:
      ness: info

server:
  port: 8080

my_jwt:
  seed: uHwuPV3iUFVMeK5m7VVZDhmkywFZoN

google:
  recaptcha:
    site: 6LcUS3gUAAAAAAc09fr__CsINv6N751HtyVw5D_j
    secret: 6LcUS3gUAAAAAFKbqkepCbRPq3PK3fPmlYprq01k