spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_release?useSSL=false
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5

  liquibase:
    change-log: classpath:/db/master.changelog.yaml

  freemarker:
    template-loader-path: classpath:/templates/email

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none

  mail:
    port: 465
    username: ${EMAIL_ADDRESS:someValue}
    password: ${EMAIL_PASSWORD:someValue}
    default-encoding: UTF-8
    protocol: smtp
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  cache:
    caffeine:
      spec: expireAfterWrite=8h

tmdbapi:
  url: http://api.themoviedb.org/3/
  apikey: ${API_TOKEN:someValue}

telegram:
  bot: movie_notify_bot
  id: movie_notify_bot
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  webInterfaceLink: ${BOT_LINK}

logging:
  level:
    com:
      ness: debug
server:
  port: 8080

my_jwt:
  seed: uHwuPV3iUFVMeK5m7VVZDhmkywFZoN

google:
  recaptcha:
    site: ${RECAPTCHA_SITE:someValue}
    secret: ${RECAPTCHA_TOKEN:someValue}

# <second> <minute> <hour> <day-of-month> <month> <day-of-week> <year>
cron:
  pattern:
    notify:
      movie: 0 0 11 * * *
      series: 0 0 12 * * *
    updateDB: 0 0 9 * * *