spring:
  #heroku datasource
  datasource:
    url: jdbc:postgresql://ec2-54-83-50-145.compute-1.amazonaws.com:5432/d44puuq4rdn72m?useSSL=false
    username: vuebzpzvdfnpna
    password: 4465743b9814c073597930ff8f66735bd70c2bd1dedb201bcce5cca3be5d069d
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update

omdbapi:
  apikey: b1e85577
  url: http://www.omdbapi.com/

telegram:
  bot: nessdebugbot

logging:
  level:
    com:
      ness: info

server:
  port: 8080